name: Luogu Hourly Punch

on:
  schedule:
    # 中国时间的 0:00 到 5:00 对应 UTC 的 16:00 到 21:00
    - cron: '0 16 * * *'  # 中国时间 0:00
    - cron: '0 17 * * *'  # 中国时间 1:00
    - cron: '0 18 * * *'  # 中国时间 2:00
    - cron: '0 19 * * *'  # 中国时间 3:00
    - cron: '0 20 * * *'  # 中国时间 4:00
    - cron: '0 21 * * *'  # 中国时间 5:00
  workflow_dispatch:  # 手动触发

jobs:
  punch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Luogu punch script
      env:
        LUOGU_UID: ${{ secrets.LUOGU_UID }}
        LUOGU_CLIENT_ID: ${{ secrets.LUOGU_CLIENT_ID }}
      run: |
        python punch_luogu.py $LUOGU_UID $LUOGU_CLIENT_ID
